import Head from 'next/head';
import { Map } from '@/components/index';
import Data from '@/data/washingtondc';
import Image from 'next/image';
import { useState } from 'react';

export default function WashingtonDC() {
  const [status, setStatus] = useState('Show');
  const [showMap, setShowMap] = useState(false);

  const MapBox = () => {
    return (
      <>
        <div className='responsive-width map'>
          <Map
            dataMarkers={Data}
            lat={38.905391483059965}
            lon={-77.03675921622916}
            zoom={11.5}
          />
        </div>
      </>
    );
  };
  return (
    <>
      <Head>
        <title>American Travel Consulting | Washington D.C.</title>
        <meta name='description' content='Generated by create next app' />
        <link rel='icon' href='/favicon.ico' />
      </Head>

      <div className='responsive-width destination__titleContainer'>
        <h1 className='destination__location'>Washington D.C.</h1>
        <h2 className='destination__country'>United States of America</h2>
      </div>
      <div className='responsive-width destination__imageWrapper'>
        <Image
          className='map__image'
          src={`/images/home/washingtondc.jpg`}
          height='400'
          width='800'
          layout='responsive'
          alt='Disney World'
        />
      </div>
      <div className='responsive-width destination__attractions'>
        <ul className='destination__list'>
          {Data.map((item) => (
            <li className='destination__item' key={item.name}>
              {item.name}
            </li>
          ))}
          <li className='destination__item'>and more...</li>
        </ul>
      </div>

      <button
        className='responsive-width destination__showButton'
        onClick={() => {
          setShowMap(!showMap);
          if (status === 'Show') {
            setStatus('Hide');
          } else {
            setStatus('Show');
          }
        }}>
        {status} Interactive Map
      </button>
      {showMap && <MapBox />}
    </>
  );
}
