import Head from 'next/head';
import Navbar from '@/components/shared/NavigationBar/Navbar';
import RequestForm from '@/components/contact/RequestForm';
export default function Contact() {
  return (
    <>
      <Head>
        <title>American Travel Company | Contact</title>
        <meta name='description' content='Generated by create next app' />
        <link rel='icon' href='/favicon.ico' />
        <meta name='viewport' content='initial-scale=1.0, width=device-width' />
      </Head>
      <Navbar />
      <h1>Contact Page</h1>
      <RequestForm />
    </>
  );
}
