import Head from 'next/head';
export default function Destinations() {
  return (
    <>
      <Head>
        <title>American Travel Company | Destinations</title>
        <meta name='description' content='Generated by create next app' />
        <link rel='icon' href='/favicon.ico' />
      </Head>
      <h1>Destinations Page</h1>
    </>
  );
}
