import Head from 'next/head';
export default function Destinations() {
  return (
    <>
      <Head>
        <title>American Travel Consulting | Destinations</title>
        <meta name='description' content='Generated by create next app' />
        <link rel='icon' href='/favicon.ico' />
      </Head>
    </>
  );
}
