import Head from 'next/head';
import Link from 'next/link';
import { TripType, Location, Testimonial } from '@/components/index';

export default function Home() {
  return (
    <>
      <Head>
        <title>American Travel Company | Home</title>
        <meta name='description' content='Generated by create next app' />
        <link rel='icon' href='/favicon.ico' />
      </Head>
      <div className='cta'>
        <div className='responsive-width cta__boundary'>
          <h1 className='cta__title cta--newline'>
            {`TRAVEL EASIER.\nTRAVEL STRESS-FREE.\nLET US DO THE WORK.`}
          </h1>
          <p className='cta__subtitle'>
            Enjoy your next group trip from start to finish without a worry in
            the world.
          </p>
          <Link href='/contact'>
            <a className='cta__link'>REQUEST A QUOTE</a>
          </Link>
        </div>
      </div>

      <div className='section'>
        <h2 className='responsive-width section__header'>Trip Types</h2>
        <div className='responsive-width typeGrid'>
          <TripType
            filename='orchestra.svg'
            title='PERFORMACE TOURS'
            altDescription='icon of a man orchestrating'
          />
          <TripType
            filename='group.svg'
            title='CORPORATE RETREATS'
            altDescription='icon of three people in buisness clothing'
          />
          <TripType
            filename='teamwork.svg'
            title='LARGE GROUP VACATIONS'
            altDescription='icon of three people in casual clothing'
          />
          <TripType
            filename='sports.svg'
            title='ATHLETIC TEAM TOURS'
            altDescription='icon with a basketball and football'
          />
          <TripType
            filename='student.svg'
            title='EDUCATIONAL TRIPS'
            altDescription='icon of three students in a blue uniform'
          />
          <TripType
            filename='family.svg'
            title='LARGE FAMILY RETREATS'
            altDescription='icon of a family'
          />
        </div>
      </div>
      <div className='section'>
        <h2 className='responsive-width section__header'>
          Popular Destinations
        </h2>
        <div className='responsive-width locationGrid'>
          <Location
            filename='orlando.jpg'
            place='Orlando, Florida'
            altDesciption='image of'
          />
          <Location
            filename='chicago.jpg'
            place='Chicago, Illinois'
            altDesciption='image of'
          />
          <Location
            filename='washingtondc.jpg'
            place='Washington D.C.'
            altDesciption='image of'
          />
          <Location
            filename='nyc.jpg'
            place='New York City, New York'
            altDesciption='image of'
          />
          <Location
            filename='sanantonio.jpg'
            place='San Antonio, Texas'
            altDesciption='image of'
          />
          <Location
            filename='philadelphia.jpg'
            place='Philadelphia, Pennsylvania'
            altDesciption='image of'
          />
        </div>
      </div>

      <div className='section section--testimonial'>
        <h2 className='responsive-width section__header'>Testimonials</h2>
        <div className='responsive-width testimonialGrid'>
          <Testimonial />
          <Testimonial />
          <Testimonial />
          <Testimonial />
          <Testimonial />
          <Testimonial />
        </div>
      </div>
    </>
  );
}
