import Head from 'next/head';
import Navbar from '@/components/shared/NavigationBar/Navbar';
import TripType from '@/components/home/TripType';
import Location from '@/components/home/Location';
import Testimonial from '@/components/home/Testimonial';

export default function Home() {
  return (
    <>
      <Head>
        <title>American Travel Company | Home</title>
        <meta name='description' content='Generated by create next app' />
        <link rel='icon' href='/favicon.ico' />
      </Head>
      <Navbar />

      <main>
        <div className='section'>
          <h2 className='responsive-width section__header'>Trip Types</h2>
          <div className='responsive-width typeGrid'>
            <TripType filename='orchestra.svg' title='PERFORMANCE ARTS TOURS' />
            <TripType filename='group.svg' title='CORPORATE RETREATS' />
            <TripType filename='teamwork.svg' title='LARGE GROUP VACATIONS' />
            <TripType filename='sports.svg' title='ATHLETIC TEAM TOURS' />
            <TripType filename='student.svg' title='EDUCATIONAL TRIPS' />
            <TripType filename='family.svg' title='LARGE FAMILY RETREATS' />
          </div>
        </div>
        <div className='section'>
          <h2 className='responsive-width section__header'>
            Popular Destinations
          </h2>
          <div className='responsive-width locationGrid'>
            <Location filename='fff.jpg' place='San Francisco, California' />
            <Location filename='fff.jpg' place='Washington D.C.' />
            <Location filename='fff.jpg' place='Orlando, Florida' />
            <Location filename='fff.jpg' place='Austin, Texas' />
            <Location filename='fff.jpg' place='Orlando, Florida' />
            <Location filename='fff.jpg' place='Austin, Texas' />
          </div>
        </div>

        <div className='section section--testimonial'>
          <h2 className='responsive-width section__header'>Testimonials</h2>
          <div className='responsive-width testimonialGrid'>
            <Testimonial />
            <Testimonial />
            <Testimonial />
            <Testimonial />
            <Testimonial />
            <Testimonial />
          </div>
        </div>
      </main>
      <footer></footer>
    </>
  );
}
