import { connectToDatabase } from '@/utils/mongodb';
import Head from 'next/head';

export default function Payment({ trips }) {
  return (
    <>
      <Head>
        <title>American Travel Consulting | Payment</title>
        <meta name='description' content='Generated by create next app' />
      </Head>
      <div className='section'>
        <h2 className='responsive-width-form section__header'>Payment Links</h2>
        <div className='responsive-width-form paymentgrid'>
          {trips.map(({ _id, date, organization, location, link }) => (
            <div key='_id' className='payment'>
              <p className='payment__organization'>{`${organization}`}</p>
              <p className='payment__location'>{`${location}`}</p>
              <p className='payment__date'>{`${date}`}</p>
              <a className='payment__link' href={link}>
                Pay
              </a>
            </div>
          ))}
        </div>
      </div>
    </>
  );
}

export const getServerSideProps = async (ctx) => {
  const { db } = await connectToDatabase();
  const trips = await db.collection('trips').find({}).toArray();

  return {
    props: {
      trips: JSON.parse(JSON.stringify(trips)),
    },
  };
};
