import Head from 'next/head';
import Navbar from '@/components/shared/NavigationBar/Navbar';
export default function Payment() {
  return (
    <>
      <Head>
        <title>American Travel Company | Payment</title>
        <meta name='description' content='Generated by create next app' />
        <link rel='icon' href='/favicon.ico' />
        <meta name='viewport' content='initial-scale=1.0, width=device-width' />
      </Head>
      <Navbar />
      <h1>Payment Page</h1>
    </>
  );
}
