import Head from 'next/head';
export default function Payment() {
  return (
    <>
      <Head>
        <title>American Travel Consulting | Payment</title>
        <meta name='description' content='Generated by create next app' />
        <link rel='icon' href='/favicon.ico' />
      </Head>
      <h1>Payment Page</h1>
    </>
  );
}
